export type CourseTransitionMedia = {
  video: string;
  poster: string;
  walkthroughAudio: string;
  walkthroughTranscript: string;
  title: string;
  alt: string;
  description: string;
};

export const courseMediaManifest: Readonly<Record<string, CourseTransitionMedia>> = {
  "FSH 101": {
    video: "/manus-storage/fleshsesh-body-literacy-first-mission-arrival_cb0255f6.mp4",
    poster: "/manus-storage/fleshsesh-body-literacy-media-reference_876f5fc1.png",
    walkthroughAudio: "/manus-storage/fleshsesh-body-literacy-unit-walkthrough_1346b4d1.mp3",
    walkthroughTranscript: "Welcome to Body Literacy. This unit offers a clear, evidence-aware way to approach terminology, variation, and support boundaries. Begin with a five-minute mission on body terminology and variation. Nothing here asks for a personal story or saves a response. Take what is useful, pause whenever you like, and continue to the next mission only if it supports your learning.",
    title: "Arrive with the idea.",
    alt: "A dark-teal adult-learning desk with closed reference materials, textured paper, a gold bookmark, and warm lamplight.",
    description: "A warm lamp illuminates a dark-teal study desk with closed neutral reference books, textured paper, and a gold bookmark as the camera slowly moves closer. No people appear.",
  },
  "FSH 102": {
    video: "/manus-storage/fleshsesh-consent-first-mission-arrival_b11534f9.mp4",
    poster: "/manus-storage/fleshsesh-consent-media-reference_04deb87d.png",
    walkthroughAudio: "/manus-storage/fleshsesh-consent-unit-walkthrough_88253ef0.mp3",
    walkthroughTranscript: "Welcome to Consent, Boundaries and Communication. This unit introduces practical language for respectful conversations, personal boundaries, and everyday choices. Begin with the five-minute mission on consent as an ongoing conversation. You do not need to disclose an experience or submit an answer. Keep the ideas that help, pause when you need to, and choose the next mission only if it feels useful.",
    title: "Make room to listen.",
    alt: "A dark-teal seminar table with two empty chairs, an unopened notebook, gold pen, coral divider card, and warm lamplight.",
    description: "A warm-lit dark-teal seminar table holds an unopened notebook, gold pen, and blush divider card between two empty chairs as the camera slowly moves across the space. No people appear.",
  },
  "FSH 103": {
    video: "/manus-storage/fleshsesh-sexual-health-first-mission-transition_4151d0d3.mp4",
    poster: "/manus-storage/fleshsesh-sexual-health-media-reference_4af9199d.png",
    walkthroughAudio: "/manus-storage/fleshsesh-sexual-health-unit-walkthrough_f610fcc5.mp3",
    walkthroughTranscript: "Welcome to Sexual Health, Hygiene and Self-Care. This unit separates clear preventive-care principles from shame-based myths and points to safe next questions. Begin with the five-minute mission on hygiene myths and body neutrality. It is general education, not personal advice or diagnosis. Nothing is recorded. Take your time, use the support routes if needed, and continue only when the next step is useful.",
    title: "Take a quiet pause.",
    alt: "A dark-teal wellbeing study counter with a folded linen towel, ceramic bowl, closed reference book, gold clasp, coral glass object, and warm light.",
    description: "Warm light moves across a dark-teal wellbeing study counter with folded linen, a ceramic bowl, a closed reference book, and a gold clasp as the camera glides slowly forward. No people appear.",
  },
  "FSH 104": {
    video: "/manus-storage/fleshsesh-relationships-first-mission-transition_3de26372.mp4",
    poster: "/manus-storage/fleshsesh-relationships-media-reference_bc62d022.png",
    walkthroughAudio: "/manus-storage/fleshsesh-relationships-unit-walkthrough_ea102cae.mp3",
    walkthroughTranscript: "Welcome to Relationships, Identity and Respect. This unit explores respectful relationship qualities, diverse identities, and the social expectations that can shape everyday choices. Begin with the five-minute mission on friendship, intimacy, and family. You are not asked to share a personal story or decide anything about yourself. Keep what is helpful, pause freely, and continue only if the next mission supports your learning.",
    title: "Leave room for respect.",
    alt: "A dark-teal shared study table with two empty chairs, closed notebooks, a gold paperclip, coral ribbon bookmark, and warm lamp light.",
    description: "A warm lamp softly illuminates a dark-teal shared study table with two empty chairs, closed notebooks, a gold paperclip, and coral ribbon as the camera glides around the table corner. No people appear.",
  },
  "FSH 105": {
    video: "/manus-storage/fleshsesh-fsh105-first-mission-transition_3502f6bb.mp4",
    poster: "/manus-storage/fleshsesh-fsh105-media-reference_a666589e.png",
    walkthroughAudio: "/manus-storage/fleshsesh-fsh105-unit-walkthrough_84527860.mp3",
    walkthroughTranscript: "In FSH 105, you’ll explore practical prevention layers, testing and treatment principles, ways to reduce stigma, and how to find trusted services. Begin with the first mission, What STIs are, for a clear foundation in respectful, everyday language. You won’t be asked for a personal story or answer, and nothing is saved. When useful, choose to pause or continue at your own pace.",
    title: "Make prevention clearer.",
    alt: "A dark-teal prevention-study desk with a closed health guide, layered cards, gold pen, and warm editorial light.",
    description: "Warm light moves across a dark-teal prevention-study desk with a closed health guide, layered reference cards, and a gold pen. No people appear.",
  },
  "FSH 201": {
    video: "/manus-storage/fleshsesh-fsh201-first-mission-transition_b7bf1535.mp4",
    poster: "/manus-storage/fleshsesh-fsh201-media-reference_62e66a44.png",
    walkthroughAudio: "/manus-storage/fleshsesh-fsh201-unit-walkthrough_9f22d177.mp3",
    walkthroughTranscript: "Welcome to FSH 201 — Contraception and Family Planning. This unit compares broad contraceptive categories and helps you prepare informed questions for a qualified health professional, without offering individual prescribing advice. Begin with the first mission, Pregnancy and fertility basics, to build a clear foundation. You are not asked to share a personal story or provide an answer, and nothing is saved. Pause or continue whenever useful.",
    title: "Make space for options.",
    alt: "A dark-teal planning desk with a closed notebook, neutral option cards, gold pencil, and soft editorial light.",
    description: "Soft light crosses a dark-teal planning desk with a closed notebook, neutral option cards, and a gold pencil arranged for a calm review. No people appear.",
  },
  "FSH 202": {
    video: "/manus-storage/fleshsesh-fsh202-first-mission-transition_808e4d72.mp4",
    poster: "/manus-storage/fleshsesh-fsh202-media-reference_a3c499f4.png",
    walkthroughAudio: "/manus-storage/fleshsesh-fsh202-unit-walkthrough_d480801f.mp3",
    walkthroughTranscript: "Welcome to FSH 202 — STI Testing, Treatment and Care Navigation. This unit will help you build a respectful testing conversation, recognise broad test categories, and consider referral pathways without diagnosing yourself or anyone else. When you’re ready, begin the first mission: Testing pathways. You won’t be asked to share a personal story, and your answers aren’t requested or saved. Take your time, and pause or continue whenever feels useful.",
    title: "Find the next right question.",
    alt: "A dark-teal care-navigation table with a closed referral folder, neutral pathway cards, and warm light.",
    description: "Warm light rests on a dark-teal care-navigation table with a closed referral folder and neutral pathway cards arranged in a simple line. No people appear.",
  },
  "FSH 203": {
    video: "/manus-storage/fleshsesh-fsh203-first-mission-transition_876d7b59.mp4",
    poster: "/manus-storage/fleshsesh-fsh203-media-reference_f238aecc.png",
    walkthroughAudio: "/manus-storage/fleshsesh-fsh203-unit-walkthrough_ed933dd6.mp3",
    walkthroughTranscript: "Welcome to FSH 203 — Pleasure, Intimacy and Sexual Communication. This unit explores how to communicate preferences and limits without entitlement, while recognising that desire can differ across people, relationships and contexts. Begin with the first mission, Pleasure literacy, to build thoughtful language for understanding choice and difference. No personal story or answer is requested or saved. Pause here, or continue when useful.",
    title: "Make room for honest language.",
    alt: "A dark-teal reading nook with two closed notebooks, a coral bookmark, a gold lamp, and warm editorial light.",
    description: "Warm light moves across a dark-teal reading nook with two closed notebooks, a coral bookmark, and a gold lamp as the camera settles into a quiet study pause. No people appear.",
  },
  "FSH 204": {
    video: "/manus-storage/fleshsesh-fsh204-first-mission-transition_4ce2b249.mp4",
    poster: "/manus-storage/fleshsesh-fsh204-media-reference_974483d6.png",
    walkthroughAudio: "/manus-storage/fleshsesh-fsh204-unit-walkthrough_03499bfd.mp3",
    walkthroughTranscript: "In FSH 204, you’ll explore how relationship systems and expectations can shape conflict, communication, and repair. Begin with the first mission, Relationship systems and expectations, and consider the patterns that influence how people respond to one another. You won’t be asked to share a personal story, and no answer is requested or saved. Pause here, or continue when it feels useful.",
    title: "Leave room for repair.",
    alt: "A warm dark-teal shared study table with two closed notebooks, a coral ribbon bookmark, and a gold pen.",
    description: "Soft light moves across a warm dark-teal shared study table with two closed notebooks, a coral ribbon bookmark, and a gold pen as the camera glides toward an open place to pause. No people appear.",
  },
  "FSH 205": {
    video: "/manus-storage/fleshsesh-fsh205-first-mission-transition_8f9ad92b.mp4",
    poster: "/manus-storage/fleshsesh-fsh205-media-reference_eaea9108.png",
    walkthroughAudio: "/manus-storage/fleshsesh-fsh205-unit-walkthrough_62231bb7.mp3",
    walkthroughTranscript: "Welcome to FSH 205 — LGBTQ+ Inclusive Sexual Health. This unit explores respectful language and affirming communication, helping you recognise diverse identities and consider inclusive referral approaches. Begin with the first mission, Language and identity, and reflect at your own pace. You will not be asked to share a personal story, and no answer is requested or saved. Pause or continue whenever useful.",
    title: "Make space for every identity.",
    alt: "A dark-teal study desk with a closed inclusive health guide, layered coral and gold language cards, and warm editorial light.",
    description: "Warm light moves across a dark-teal study desk with a closed inclusive health guide and layered coral and gold language cards arranged for a calm review. No people appear.",
  },
  "FSH 206": {
    video: "/manus-storage/fleshsesh-fsh206-first-mission-transition_70c30cac.mp4",
    poster: "/manus-storage/fleshsesh-fsh206-media-reference_dc660583.png",
    walkthroughAudio: "/manus-storage/fleshsesh-fsh206-unit-walkthrough_692d90b1.mp3",
    walkthroughTranscript: "In FSH 206 — Digital Intimacy, Privacy and Safety, you’ll explore how privacy and consent shape safer digital communication, then develop a practical incident-response plan. Begin with the first mission, Digital consent, and consider the choices that help communication remain respectful and secure. You won’t be asked for, or have any personal story or answer saved. Pause here, or continue when useful.",
    title: "Pause before you share.",
    alt: "A dark-teal desk with a closed laptop, privacy notebook, gold lock-shaped paperclip, and soft coral light.",
    description: "Soft coral light moves across a dark-teal desk with a closed laptop, privacy notebook, and gold lock-shaped paperclip arranged for a quiet digital-safety pause. No people appear.",
  },
  "FSH 207": {
    video: "/manus-storage/fleshsesh-fsh207-first-mission-transition_d7b4ae12.mp4",
    poster: "/manus-storage/fleshsesh-fsh207-media-reference_4aa7592d.png",
    walkthroughAudio: "/manus-storage/fleshsesh-fsh207-unit-walkthrough_02aa3c0e.mp3",
    walkthroughTranscript: "In FSH 207, we’ll explore how sexual wellbeing can support mental health, using respectful, supportive language and recognising when qualified care may be helpful. To begin, open the first mission: Definitions of sexual wellbeing. You won’t be asked to share a personal story or provide an answer, and nothing is requested or saved. Take your time, and pause or continue whenever feels useful.",
    title: "Start with a kinder question.",
    alt: "A softly lit dark-teal reading table with a closed wellbeing journal, coral bookmark, ceramic cup, and gold lamp.",
    description: "A gold lamp creates a calm pool of light on a dark-teal reading table with a closed wellbeing journal, coral bookmark, and ceramic cup. No people appear.",
  },
  "FSH 301": {
    video: "/manus-storage/fleshsesh-fsh301-first-mission-transition_ce12a270.mp4",
    poster: "/manus-storage/fleshsesh-fsh301-media-reference_82103de2.png",
    walkthroughAudio: "/manus-storage/fsh301-unit-walkthrough_f0da8951.mp3",
    walkthroughTranscript: "Welcome to FSH 301 — Reproductive Health, Fertility and Life Planning. This unit looks at fertility variation, reproductive pathways, and uncertainty with care and plain language. Your first mission is to separate general education from personal clinical advice and identify one question you could take to a qualified professional. You never need to share a personal story here, and nothing is saved from this walkthrough. When you are ready, begin with the first mission, or pause and return to the atlas.",
    title: "Make room for uncertainty.",
    alt: "A dark-teal seminar room with an open notebook, textured paper, and warm side light arranged for reflective study.",
    description: "A warm side light drifts across a dark-teal seminar room with an open notebook and textured paper as the camera pauses on the study setting. No people appear.",
  },
  "FSH 302": {
    video: "/manus-storage/fleshsesh-fsh302-first-mission-transition_8c831a40.mp4",
    poster: "/manus-storage/fleshsesh-fsh302-media-reference_a8748a96.png",
    walkthroughAudio: "/manus-storage/fsh302-unit-walkthrough_f8405c56.mp3",
    walkthroughTranscript: "Welcome to FSH 302 — Kink Education, Negotiation and Safety. This unit explores consent, power, negotiation, risk literacy, and aftercare without explicit demonstration. Your first mission is to identify the boundaries and safety questions that should be clarified before any adult activity. You never need to share a personal story here, and nothing is saved from this walkthrough. When you are ready, begin with the first mission, or pause and return to the atlas.",
    title: "Start with clear boundaries.",
    alt: "A dark-teal listening room with two empty chairs, textured walls, and soft warm light arranged for a respectful pause.",
    description: "Soft warm light moves across a dark-teal listening room with two empty chairs as the camera makes a slow, respectful pause. No people appear.",
  },
  "FSH 303": {
    video: "/manus-storage/fleshsesh-fsh303-first-mission-transition_81cb6340.mp4",
    poster: "/manus-storage/fleshsesh-fsh303-media-reference_f9a33eca.png",
    walkthroughAudio: "/manus-storage/fsh303-unit-walkthrough_cc800bbd.mp3",
    walkthroughTranscript: "Welcome to FSH 303 — Communication for Educators and Advocates. This unit is about translating evidence into plain language, facilitating inclusive discussion, and knowing when to refer beyond your competence. Your first mission is to turn one complex idea into a clear, respectful explanation for an adult learner. You never need to share a personal story here, and nothing is saved from this walkthrough. When you are ready, begin with the first mission, or pause and return to the atlas.",
    title: "Make complex ideas clearer.",
    alt: "A dark-teal library table with a closed journal, a small plant, and warm lamp light arranged for focused study.",
    description: "Warm lamp light moves across a dark-teal library table with a closed journal and small plant as the camera settles into a quiet teaching pause. No people appear.",
  },
  "FSH 304": {
    video: "/manus-storage/fleshsesh-fsh304-first-mission-transition_04ca4952.mp4",
    poster: "/manus-storage/fleshsesh-fsh304-media-reference_08d8327d.png",
    walkthroughAudio: "/manus-storage/fsh304-unit-walkthrough_882b0e2c.mp3",
    walkthroughTranscript: "Welcome to FSH 304 — Sexual Rights, Ethics, Power and Social Context. This unit examines autonomy, dignity, power, privacy, safeguarding, and institutional responsibility. Your first mission is to notice how a system or setting can support choice, access, and respect without speaking over the people it affects. You never need to share a personal story here, and nothing is saved from this walkthrough. When you are ready, begin with the first mission, or pause and return to the atlas.",
    title: "Notice who gets a choice.",
    alt: "A dark-teal desk with a face-down phone, closed notebook, and warm lamp arranged for a privacy-first study pause.",
    description: "Warm lamp light moves across a dark-teal desk with a face-down phone and closed notebook as the camera pauses on a privacy-first study setting. No people appear.",
  },
  "FSH 305": {
    video: "/manus-storage/fleshsesh-fsh305-first-mission-transition_2e674d15.mp4",
    poster: "/manus-storage/fleshsesh-fsh305-media-reference_ad7149a5.png",
    walkthroughAudio: "/manus-storage/fleshsesh-fsh305-unit-walkthrough_9aefc75f.mp3",
    walkthroughTranscript: "Welcome to Inclusive Service and Curriculum Design. This unit is a practical introduction to audience needs, accessible learning design, curriculum mapping, and evidence-aware evaluation. Begin with the first free mission by noticing one learner need and choosing one design question to carry forward. You never need to share a personal story here. This walkthrough is optional, nothing is saved from listening, and you can pause or continue at your own pace.",
    title: "Make inclusive design practical.",
    alt: "A dark blue-black study table with a folded neutral information guide, soft sage accents, and warm editorial light.",
    description: "Warm light moves across a dark blue-black study table with a folded neutral information guide and soft sage accents as the camera pauses on the paper texture. No people appear.",
  },
  "FSH 401": {
    video: "/manus-storage/fleshsesh-fsh401-first-mission-transition_c216967a.mp4",
    poster: "/manus-storage/fleshsesh-fsh401-media-reference_481f2df1.png",
    walkthroughAudio: "/manus-storage/fleshsesh-fsh401-unit-walkthrough_2f51a21d.mp3",
    walkthroughTranscript: "Welcome to Advanced Advocacy and Community Practice. This unit explores community assessment, partnership, power mapping, implementation, and respectful outcome evaluation. Begin with the first free mission by noticing one community need and choosing one question to carry into a co-designed response. You never need to share a personal story here. This walkthrough is optional, nothing is saved from listening, and you can pause or return whenever you choose.",
    title: "Map change with care.",
    alt: "An obsidian reading room with an open blank notebook, brass desk lamp, layered paper, and soft gold light.",
    description: "A warm light shifts across an obsidian reading room with an open blank notebook, brass desk lamp, and layered paper as the camera makes a gentle reflective drift. No people appear.",
  },
  "FSH 402": {
    video: "/manus-storage/fleshsesh-fsh402-first-mission-transition_c2cf912c.mp4",
    poster: "/manus-storage/fleshsesh-fsh402-media-reference_b8c6e885.png",
    walkthroughAudio: "/manus-storage/fleshsesh-fsh402-unit-walkthrough_acf0c17e.mp3",
    walkthroughTranscript: "Welcome to Advanced Consent and Relationship Facilitation. This unit explores complex consent conversations, capacity, communication, mediation boundaries, and survivor-centred referral. Begin with the first free mission by noticing one boundary that needs clear language and choosing one safe next step. You never need to share a personal story here. This walkthrough is optional, nothing is saved from listening, and you can pause or return whenever you choose.",
    title: "Hold the boundary.",
    alt: "A quiet communal reading table with three closed notebooks, warm lamp glow, deep teal, and blush accents.",
    description: "Warm lamp light moves across a quiet communal reading table with three closed notebooks as the camera makes a gentle inclusive pause. No people appear.",
  },
  "FSH 403": {
    video: "/manus-storage/fleshsesh-fsh403-first-mission-transition_a2e7ea3f.mp4",
    poster: "/manus-storage/fleshsesh-fsh403-media-reference_a135bf54.png",
    walkthroughAudio: "/manus-storage/fleshsesh-fsh403-unit-walkthrough_3e75168c.mp3",
    walkthroughTranscript: "Welcome to Evidence, Evaluation and AI in Sexual Education. This unit explores evidence appraisal, measurement, bias, privacy, algorithmic accountability, and human oversight. Begin with the first free mission by asking what evidence supports one claim and choosing one careful next step. You never need to share a personal story here. This walkthrough is optional, nothing is saved from listening, and you can pause or return whenever you choose.",
    title: "Ask what the evidence shows.",
    alt: "A dark editorial desk with a closed notebook, brass key, frosted glass, and soft coral light.",
    description: "Soft coral light shifts across a dark editorial desk with a closed notebook, brass key, and frosted glass as the camera makes a quiet digital-safety pause. No people appear.",
  },
  "FSH 404": {
    video: "/manus-storage/fleshsesh-fsh404-first-mission-transition_2a3efd23.mp4",
    poster: "/manus-storage/fleshsesh-fsh404-media-reference_1765be71.png",
    walkthroughAudio: "/manus-storage/fleshsesh-fsh404-unit-walkthrough_ecbbf54e.mp3",
    walkthroughTranscript: "Welcome to Capstone: Sexual Wellness Education Portfolio. This unit brings together evidence, inclusion, ethics, safeguarding, and referral practice in a structured educational portfolio. Begin with the first free mission by clarifying one proposal question and choosing one evidence-aware next step. You never need to share a personal story here. This walkthrough is optional, nothing is saved from listening, and you can pause or return whenever you choose.",
    title: "Notice who gets a choice.",
    alt: "A quiet archive table with blank cards, a closed book, brass paperweight, and warm gold light.",
    description: "Warm gold light moves across a quiet archive table with blank cards, a closed book, and brass paperweight as the camera makes a calm ethics and social-context pause. No people appear.",
  },
};
