import { ArrowLeft, ArrowUpRight, BookOpen, Headphones, Library } from "lucide-react";
import { useLocation } from "wouter";
import { campusFacilities, type FacilityId } from "@shared/campusFacilities";

const wordmark = "/manus-storage/fleshsesh-academy-lockup-primary_c4730d25.png";
const placeIcons: Record<FacilityId, typeof BookOpen> = { classroom: BookOpen, "student-services": Headphones, auditorium: Library };

export default function Campus() {
  const [, setLocation] = useLocation();
  const locationSearch = typeof window !== "undefined" ? window.location.search : "";
  const previewMode = import.meta.env.DEV && new URLSearchParams(locationSearch).get("preview") === "academy";
  const withPreview = (path: string) => previewMode ? path + (path.includes("?") ? "&" : "?") + "preview=academy" : path;

  return <main className="min-h-screen overflow-x-hidden bg-[#061018] text-[#eff4f1]"><header className="sticky top-0 z-40 border-b border-white/10 bg-[#061018]/90 backdrop-blur-xl"><div className="mx-auto flex min-h-[88px] max-w-[1500px] items-center justify-between gap-3 px-5 py-2 sm:px-8 lg:px-12"><button onClick={() => setLocation(withPreview("/"))} className="inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.14em] text-[#f1dca4]"><ArrowLeft className="h-3.5 w-3.5" /> eCampus</button><img src={wordmark} alt="fleshsesh | academy" className="h-[58px] w-[180px] object-cover object-center sm:h-[72px] sm:w-[240px]" /><button onClick={() => setLocation(withPreview("/orientation"))} className="text-[10px] font-bold uppercase tracking-[.14em] text-[#f1dca4]">Start mission</button></div></header>
    <section className="relative overflow-hidden border-b border-white/10 px-5 py-16 sm:px-8 lg:px-12 lg:py-24"><img src="/manus-storage/fleshsesh-law-library-editorial_d61126d2.jpg" alt="" className="absolute inset-0 h-full w-full object-cover opacity-25" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(4,13,20,.98),rgba(4,13,20,.74),rgba(4,13,20,.5))]" /><div className="relative mx-auto max-w-[1500px]"><p className="text-[10px] font-bold uppercase tracking-[.22em] text-[#e6c887]">Background support</p><h1 className="mt-6 max-w-4xl font-display text-[clamp(4.5rem,9vw,9rem)] leading-[.7] tracking-[-.07em]">You do not need<br /><em className="text-[#e49aa9]">a campus map.</em></h1><p className="mt-8 max-w-xl text-base leading-7 text-[#d0ded9]">Start a short mission first. These spaces are only here when you need a simpler explanation, a practical next step, or more depth.</p><button onClick={() => setLocation(withPreview("/orientation"))} className="mt-9 inline-flex items-center gap-3 bg-[#e49aa9] px-6 py-5 text-xs font-bold uppercase tracking-[.16em] text-[#061018]">Start one mission <ArrowUpRight className="h-4 w-4" /></button></div></section>
    <section className="px-5 py-12 sm:px-8 lg:px-12 lg:py-16"><div className="mx-auto max-w-[1500px]"><div className="max-w-xl"><p className="text-[9px] font-bold uppercase tracking-[.16em] text-[#e6c887]">Only if you need them</p><h2 className="mt-4 font-display text-5xl leading-[.8]">Three quiet<br /><em className="text-[#e49aa9]">support spaces.</em></h2></div><div className="mt-10 grid gap-4 md:grid-cols-3">{campusFacilities.map((place) => { const Icon = placeIcons[place.id]; return <article key={place.id} className="border border-white/15 bg-[#0b1c26] p-6"><Icon className="h-5 w-5 text-[#e6c887]" /><p className="mt-8 text-[9px] font-bold uppercase tracking-[.16em] text-[#e6c887]">{place.eyebrow}</p><h3 className="mt-4 font-display text-4xl leading-[.82]">{place.label}</h3><p className="mt-5 text-sm leading-6 text-[#c6d5d1]">{place.description}</p><button onClick={() => setLocation(withPreview(`/campus/${place.id}`))} className="mt-7 inline-flex items-center gap-2 border-b border-[#e6c887]/60 pb-1 text-[10px] font-bold uppercase tracking-[.14em] text-[#f1dca4]">Open only if useful <ArrowUpRight className="h-3.5 w-3.5" /></button></article>; })}</div></div></section>
  </main>;
}
