import { useEffect, useMemo, useState } from "react";
import { useLocation, useRoute } from "wouter";
import { ArrowLeft, ArrowUpRight, BookOpen, Compass, GraduationCap, Lightbulb, ShieldCheck, Sparkles } from "lucide-react";
import { campusFacilities, type FacilityId } from "@shared/campusFacilities";
import { courseByCode } from "@shared/courseCatalog";

const emblem = "/manus-storage/fleshsesh-academy-emblem_79c8c72e.png";
const wordmark = "/manus-storage/fleshsesh-academy-lockup-primary_c4730d25.png";
const ageStorageKey = "fleshsesh_academy_age_confirmed_v2";

function isFacilityId(value: string | undefined): value is FacilityId {
  return Boolean(value && campusFacilities.some((facility) => facility.id === value));
}

export default function FacilityRoom() {
  const [, params] = useRoute("/campus/:facility");
  const [, setLocation] = useLocation();
  const previewMode = import.meta.env.DEV && new URLSearchParams(window.location.search).get("preview") === "academy";
  const [ageReady, setAgeReady] = useState(false);
  const [ageConfirmed, setAgeConfirmed] = useState(previewMode);
  const [promptIndex, setPromptIndex] = useState(0);
  const facility = useMemo(() => campusFacilities.find((item) => item.id === (isFacilityId(params?.facility) ? params?.facility : "eclinic")) ?? campusFacilities[0], [params?.facility]);
  const campusPath = previewMode ? "/campus?preview=academy" : "/campus";
  const homePath = previewMode ? "/?preview=academy" : "/";
  const pathwayPath = `/learn?facility=${facility.id}${previewMode ? "&preview=academy" : ""}`;
  const facultyPath = `/?faculty=${facility.room.faculty.id}${previewMode ? "&preview=academy" : ""}#faculty`;
  const otherRooms = campusFacilities.filter((item) => item.id !== facility.id);

  useEffect(() => {
    if (!previewMode) setAgeConfirmed(window.localStorage.getItem(ageStorageKey) === "true");
    setAgeReady(true);
  }, [previewMode]);

  useEffect(() => {
    if (!ageReady || !ageConfirmed || facility.id !== "esports") return;
    const lobbyButton = Array.from(document.querySelectorAll("button")).find((button) => button.textContent?.toLowerCase().includes("open non-live lobby"));
    if (!lobbyButton || document.getElementById("arena-readiness-link")) return;
    const readinessLink = document.createElement("button");
    readinessLink.id = "arena-readiness-link";
    readinessLink.type = "button";
    readinessLink.textContent = "Review connector readiness";
    readinessLink.className = "mt-4 block text-[10px] font-bold uppercase tracking-[.14em] text-[#f1dca4] underline decoration-[#e6c887]/60 underline-offset-4 transition hover:text-[#e49aa9]";
    readinessLink.addEventListener("click", () => setLocation(`/campus/esports/readiness${previewMode ? "?preview=academy" : ""}`));
    lobbyButton.parentElement?.append(readinessLink);
    return () => readinessLink.remove();
  }, [ageReady, ageConfirmed, facility.id, previewMode, setLocation]);

  if (!ageReady) return <div className="min-h-screen bg-[#061018]" />;
  if (!ageConfirmed) return <main className="grid min-h-screen place-items-center bg-[#061018] px-5 text-[#eff4f1]"><section className="max-w-xl border border-white/15 bg-[#0b1c26] p-8 sm:p-12"><img src={wordmark} alt="fleshsesh | academy" className="h-[96px] w-[340px] max-w-full object-cover object-center" /><p className="mt-10 text-[10px] font-bold uppercase tracking-[.22em] text-[#e6c887]">Room entry</p><h1 className="mt-4 font-display text-6xl leading-[.78]">Confirm the<br /><em className="text-[#e49aa9]">adult gateway.</em></h1><p className="mt-6 text-sm leading-6 text-[#c8d6d2]">Each visual room shares the eCampus adult-access boundary.</p><button onClick={() => setLocation(homePath)} className="mt-9 inline-flex items-center gap-2 bg-[#e49aa9] px-5 py-4 text-xs font-bold uppercase tracking-[.14em] text-[#061018]">Return to entry <ArrowUpRight className="h-4 w-4" /></button></section></main>;

  return <main className="min-h-screen overflow-x-hidden bg-[#061018] text-[#eff4f1]"><header className="sticky top-0 z-40 border-b border-white/10 bg-[#061018]/85 backdrop-blur-xl"><div className="mx-auto flex min-h-[88px] py-2 max-w-[1600px] items-center justify-between px-5 sm:px-8 lg:px-12"><button onClick={() => setLocation(campusPath)} className="flex items-center gap-3" aria-label="Return to campus"><img src={emblem} alt="" className="h-9 w-9 rounded-full ring-1 ring-[#e6c887]/55" /><span className="hidden text-[10px] font-bold uppercase tracking-[.16em] text-[#e6c887] sm:block">Campus map</span></button><img src={wordmark} alt="fleshsesh | academy" className="h-[58px] w-[180px] object-cover object-center sm:h-[72px] sm:w-[240px]" /><button onClick={() => setLocation(pathwayPath)} className="inline-flex items-center gap-2 border-b border-[#e6c887]/60 pb-1 text-[10px] font-bold uppercase tracking-[.14em] text-[#f1dca4]">Mapped units <ArrowUpRight className="h-3.5 w-3.5" /></button></div></header>

    <section className="relative flex min-h-[76svh] items-end overflow-hidden px-5 pb-14 pt-20 sm:px-8 lg:px-12 lg:pb-20"><img src={facility.image} alt="" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(4,13,20,.96),rgba(4,13,20,.72)_40%,rgba(4,13,20,.18)_100%)]" /><div className="absolute inset-x-0 bottom-0 h-[48%] bg-[linear-gradient(0deg,rgba(4,13,20,.98),transparent)]" /><div className="relative mx-auto grid w-full max-w-[1600px] gap-10 lg:grid-cols-[1fr_410px] lg:items-end"><div><button onClick={() => setLocation(campusPath)} className="inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.16em] text-[#d2dfdb] transition hover:text-[#e6c887]"><ArrowLeft className="h-3.5 w-3.5" /> Campus map</button><p className="mt-20 text-[10px] font-bold uppercase tracking-[.24em] text-[#e6c887]">{facility.eyebrow}</p><h1 className="mt-6 font-display text-[clamp(5rem,10vw,10rem)] leading-[.69] tracking-[-.075em]">{facility.label}<br /><em className="text-[#e49aa9]">{facility.room.studioName}.</em></h1><p className="mt-9 max-w-2xl text-base leading-7 text-[#d3dfdb]">{facility.room.studioIntroduction}</p></div><aside className="border border-white/20 bg-[#071720]/72 p-5 backdrop-blur-md"><p className="text-[9px] font-bold uppercase tracking-[.18em] text-[#e6c887]">Room boundary</p><p className="mt-4 font-display text-4xl leading-[.82]">Pause is part<br />of the <em className="text-[#e49aa9]">design.</em></p><p className="mt-5 text-sm leading-6 text-[#c9d8d4]">{facility.note}</p><button onClick={() => setLocation(pathwayPath)} className="mt-7 inline-flex items-center gap-2 bg-[#e6c887] px-4 py-3 text-[10px] font-bold uppercase tracking-[.14em] text-[#061018]">Open pathway <BookOpen className="h-3.5 w-3.5" /></button></aside></div></section>

    <section className="bg-[#102630] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1600px] gap-10 lg:grid-cols-[.72fr_1.28fr]"><div><p className="text-[10px] font-bold uppercase tracking-[.22em] text-[#e6c887]">Three ways to enter</p><h2 className="mt-5 font-display text-6xl leading-[.78] tracking-[-.055em] sm:text-7xl">Pick your<br /><em className="text-[#e49aa9]">learning posture.</em></h2><p className="mt-7 max-w-lg text-sm leading-6 text-[#c7d6d2]">No room requires personal disclosure. Each mode gives you a distinct way to approach the subject before deciding whether to continue into a formal unit.</p>{facility.id === "esports" && <div className="mt-8 border border-[#e6c887]/35 bg-[#071720] p-5"><p className="text-[9px] font-bold uppercase tracking-[.16em] text-[#e6c887]">Arena access</p><p className="mt-3 text-xs leading-5 text-[#c5d4d0]">The local tournament lobby is a consent-first preview only. It offers pause, emergency-stop, and disconnect boundaries without a live provider or personal-device connection.</p><button onClick={() => setLocation(`${campusPath}#arena-lobby`)} className="mt-5 inline-flex items-center gap-2 border-b border-[#e6c887]/60 pb-1 text-[10px] font-bold uppercase tracking-[.14em] text-[#f1dca4]">Open non-live lobby <ArrowUpRight className="h-3.5 w-3.5" /></button></div>}</div><div className="grid gap-3 md:grid-cols-3">{facility.room.learningModes.map((mode, index) => <article key={mode.title} className="relative min-h-[290px] overflow-hidden border border-white/10 bg-[#071720] p-6"><span className="font-display text-6xl leading-none text-[#e6c887]">0{index + 1}</span><h3 className="mt-14 font-display text-4xl leading-[.84]">{mode.title}</h3><p className="mt-5 text-sm leading-6 text-[#bdcec9]">{mode.copy}</p></article>)}</div></div></section>

    <section className="bg-[#061018] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1600px] gap-10 xl:grid-cols-[.68fr_1.32fr]"><div><p className="inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.22em] text-[#e6c887]"><Lightbulb className="h-3.5 w-3.5" /> Private learning lens</p><h2 className="mt-5 font-display text-6xl leading-[.78] tracking-[-.055em] sm:text-7xl">Think without<br /><em className="text-[#e49aa9]">telling on yourself.</em></h2><p className="mt-7 max-w-lg text-sm leading-6 text-[#c6d6d1]">Prompts are optional internal frames for learning. They are not a request to document your personal experience and there is no correct disclosure.</p></div><div className="border border-white/15 bg-[#0b1c26] p-5 sm:p-8"><p className="text-[9px] font-bold uppercase tracking-[.18em] text-[#e6c887]">Current prompt</p><p className="mt-5 font-display text-5xl leading-[.82] text-[#f3f1ea]">{facility.room.reflectionPrompts[promptIndex]}</p><div className="mt-10 grid gap-2">{facility.room.reflectionPrompts.map((prompt, index) => <button key={prompt} onClick={() => setPromptIndex(index)} className={`flex items-center justify-between gap-4 border px-4 py-4 text-left text-xs leading-5 transition ${promptIndex === index ? "border-[#e49aa9] bg-[#3a2230] text-[#f7e9ec]" : "border-white/10 text-[#c4d4cf] hover:border-[#e6c887]/55"}`}><span>{prompt}</span><ArrowUpRight className="h-4 w-4 shrink-0" /></button>)}</div></div></div></section>

    <section className="relative overflow-hidden bg-[#102630] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><img src={facility.image} alt="" className="pointer-events-none absolute inset-y-0 right-0 h-full w-[38%] object-cover opacity-15" /><div className="pointer-events-none absolute inset-y-0 right-0 w-[65%] bg-[linear-gradient(90deg,#102630,rgba(16,38,48,.35))]" /><div className="relative mx-auto grid max-w-[1600px] gap-10 xl:grid-cols-[.68fr_1.32fr]"><div><p className="text-[10px] font-bold uppercase tracking-[.22em] text-[#e6c887]">Your actual pathway</p><h2 className="mt-5 font-display text-6xl leading-[.78] tracking-[-.055em] sm:text-7xl">This room<br /><em className="text-[#e49aa9]">becomes study.</em></h2><p className="mt-7 max-w-lg text-sm leading-6 text-[#c5d4d0]">The room points to the actual eCampus units below. Open one to read the teaching outcome and enrolment route; return to the mapped collection whenever you wish.</p><button onClick={() => setLocation(pathwayPath)} className="mt-8 inline-flex items-center gap-2 bg-[#e6c887] px-5 py-4 text-xs font-bold uppercase tracking-[.14em] text-[#061018]">Open full pathway <BookOpen className="h-4 w-4" /></button></div><div className="grid gap-2">{facility.courseCodes.map((code, index) => { const course = courseByCode.get(code); if (!course) return null; const coursePath = `/learn?course=${encodeURIComponent(code)}&facility=${facility.id}${previewMode ? "&preview=academy" : ""}`; return <button key={code} onClick={() => setLocation(coursePath)} className="group grid gap-4 border border-white/10 bg-[#071720]/90 p-5 text-left transition hover:border-[#e6c887]/65 sm:grid-cols-[74px_1fr_auto] sm:items-center"><span className="font-display text-4xl text-[#e6c887]">0{index + 1}</span><span><span className="text-[9px] font-bold uppercase tracking-[.15em] text-[#e49aa9]">{course.code} · level {course.level}</span><span className="mt-2 block font-display text-3xl leading-none transition group-hover:text-[#f0b1bb]">{course.title}</span><span className="mt-2 block text-xs text-[#b8c9c4]">{course.subtitle}</span></span><span className="inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.13em] text-[#f1dca4]">View unit <ArrowUpRight className="h-3.5 w-3.5" /></span></button> })}</div></div></section>

    <section className="bg-[#071720] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1600px] gap-10 xl:grid-cols-[.7fr_1.3fr]"><div><p className="text-[10px] font-bold uppercase tracking-[.22em] text-[#e6c887]">Faculty handoff</p><h2 className="mt-5 font-display text-6xl leading-[.78] tracking-[-.055em] sm:text-7xl">Continue with<br /><em className="text-[#e49aa9]">{facility.room.faculty.name}.</em></h2><p className="mt-7 max-w-lg text-sm leading-6 text-[#c6d5d1]">The faculty studio is an automated learning guide with a scoped educational role. It does not request personal history or provide individual diagnosis, treatment, legal advice, or crisis services.</p><button onClick={() => setLocation(facultyPath)} className="mt-8 inline-flex items-center gap-2 bg-[#e49aa9] px-5 py-4 text-xs font-bold uppercase tracking-[.14em] text-[#061018]">Open faculty folio <Sparkles className="h-4 w-4" /></button></div><div className="grid gap-2 md:grid-cols-3"><div className="border border-white/10 bg-[#0b1c26] p-6"><GraduationCap className="h-5 w-5 text-[#e6c887]" /><p className="mt-10 text-[9px] font-bold uppercase tracking-[.16em] text-[#e6c887]">Faculty role</p><p className="mt-4 font-display text-4xl leading-[.85]">{facility.room.faculty.role}</p></div><div className="border border-white/10 bg-[#0b1c26] p-6"><Compass className="h-5 w-5 text-[#e6c887]" /><p className="mt-10 text-[9px] font-bold uppercase tracking-[.16em] text-[#e6c887]">Suggested question</p><p className="mt-4 text-sm leading-6 text-[#c8d8d3]">“{facility.room.faculty.prompt}”</p></div><div className="border border-[#e6c887]/25 bg-[#152d38] p-6"><ShieldCheck className="h-5 w-5 text-[#e6c887]" /><p className="mt-10 text-[9px] font-bold uppercase tracking-[.16em] text-[#e6c887]">Teaching boundary</p><p className="mt-4 text-sm leading-6 text-[#c8d8d3]">{facility.room.faculty.handoff}</p></div></div></div></section>

    <section className="bg-[#030b11] px-5 py-16 sm:px-8 lg:px-12"><div className="mx-auto max-w-[1600px]"><p className="text-[10px] font-bold uppercase tracking-[.22em] text-[#e6c887]">Move through the campus</p><div className="mt-7 grid gap-3 md:grid-cols-3">{otherRooms.map((room) => <button key={room.id} onClick={() => setLocation(`/campus/${room.id}${previewMode ? "?preview=academy" : ""}`)} className="group relative min-h-[260px] overflow-hidden border border-white/10 text-left"><img src={room.image} alt="" className="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-[1.05]" /><div className="absolute inset-0 bg-[linear-gradient(0deg,rgba(4,13,20,.96),rgba(4,13,20,.08)_75%)]" /><div className="relative flex h-full flex-col justify-end p-5"><p className="text-[9px] font-bold uppercase tracking-[.16em] text-[#e6c887]">{room.eyebrow}</p><p className="mt-2 font-display text-5xl leading-[.8]">{room.label}</p><span className="mt-5 inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.14em] text-[#f1dca4]">Enter room <ArrowUpRight className="h-3.5 w-3.5" /></span></div></button>)}</div></div></section>

    <footer className="border-t border-white/10 bg-[#030b11] px-5 py-8 sm:px-8 lg:px-12"><div className="mx-auto flex max-w-[1600px] flex-col justify-between gap-4 text-[10px] font-bold uppercase tracking-[.14em] text-[#9eb2ae] sm:flex-row sm:items-center"><div className="flex items-center gap-3"><img src={wordmark} alt="fleshsesh | academy" className="h-12 w-[200px] object-cover object-center" /><span>adult learning with agency</span></div><button onClick={() => setLocation(homePath)} className="inline-flex items-center gap-2 text-[#f1dca4]">Return to eCampus <ArrowUpRight className="h-3.5 w-3.5" /></button></div></footer>
  </main>;
}
