import { useEffect, useMemo, useState } from "react";
import { useLocation, useRoute } from "wouter";
import { ArrowLeft, ArrowUpRight, BookOpen, Compass, GraduationCap, Lightbulb, ShieldCheck, Sparkles } from "lucide-react";
import { campusFacilities, type FacilityId } from "@shared/campusFacilities";
import { courseByCode } from "@shared/courseCatalog";

const emblem = "/manus-storage/fleshsesh-academy-emblem_79c8c72e.png";
const wordmark = "/manus-storage/fleshsesh-academy-wordmark_f79fa930.png";
const ageStorageKey = "fleshsesh_academy_age_confirmed_v2";

function isFacilityId(value: string | undefined): value is FacilityId {
  return Boolean(value && campusFacilities.some((facility) => facility.id === value));
}

export default function FacilityRoom() {
  const [, params] = useRoute("/campus/:facility");
  const [, setLocation] = useLocation();
  const previewMode = import.meta.env.DEV && new URLSearchParams(window.location.search).get("preview") === "academy";
  const [ageConfirmed, setAgeConfirmed] = useState(previewMode);
  const [ageChecked, setAgeChecked] = useState(false);
  const [selectedPrompt, setSelectedPrompt] = useState(0);
  const facilityId = isFacilityId(params?.facility) ? params.facility : "eclinic";
  const facility = useMemo(() => campusFacilities.find((item) => item.id === facilityId) ?? campusFacilities[0], [facilityId]);
  const homePath = previewMode ? "/?preview=academy" : "/";
  const campusPath = previewMode ? "/campus?preview=academy" : "/campus";
  const pathwayPath = `/learn?facility=${facility.id}${previewMode ? "&preview=academy" : ""}`;
  const facultyPath = `/?faculty=${facility.room.faculty.id}${previewMode ? "&preview=academy" : ""}#faculty`;
  const nearbyRooms = campusFacilities.filter((item) => item.id !== facility.id);

  useEffect(() => {
    if (!previewMode) setAgeConfirmed(window.localStorage.getItem(ageStorageKey) === "true");
    setAgeChecked(true);
  }, [previewMode]);

  if (!ageChecked) return <div className="min-h-screen bg-[#0d1822]" />;
  if (!ageConfirmed) {
    return <main className="grid min-h-screen place-items-center bg-[#0d1822] px-5 text-[#f3f7f4]"><section className="max-w-xl border border-[#d8bd82]/30 bg-[#152532] p-8 shadow-2xl sm:p-10"><img src={wordmark} alt="fleshsesh | academy" className="h-12 w-[220px] object-contain object-left" /><p className="mt-10 text-[10px] font-bold uppercase tracking-[0.22em] text-[#d8bd82]">Campus access</p><h1 className="mt-4 font-display text-5xl leading-[0.88]">Confirm the adult gateway before entering this room.</h1><p className="mt-6 text-sm leading-6 text-[#c6d3d0]">Facility rooms contain adult-learning material and share the eCampus 18+ access boundary.</p><button onClick={() => setLocation(homePath)} className="mt-8 inline-flex items-center gap-2 bg-[#df8997] px-5 py-4 text-xs font-bold uppercase tracking-[0.14em] text-[#152532] transition hover:bg-[#eea6b1] active:scale-[0.97]">Return to age gateway <ArrowUpRight className="h-4 w-4" /></button></section></main>;
  }

  return <main className="min-h-screen overflow-x-hidden bg-[#0d1822] text-[#f3f7f4] selection:bg-[#df8997] selection:text-[#152532]">
    <header className="sticky top-0 z-30 border-b border-white/10 bg-[#0d1822]/92 backdrop-blur-xl"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-5 py-4 sm:px-8 lg:px-12"><button onClick={() => setLocation(campusPath)} className="flex items-center gap-3 text-left" aria-label="Return to campus hub"><img src={emblem} alt="" className="h-10 w-10 rounded-full ring-1 ring-[#d8bd82]/35" /><span className="hidden text-[10px] font-bold uppercase tracking-[0.18em] text-[#d8bd82] sm:block">Campus hub</span></button><img src={wordmark} alt="fleshsesh | academy" className="h-10 w-[175px] object-contain" /><button onClick={() => setLocation(pathwayPath)} className="inline-flex items-center gap-2 border-b border-[#d8bd82]/65 pb-1 text-[10px] font-bold uppercase tracking-[0.14em] text-[#f2d59e] transition hover:border-[#df8997] hover:text-[#ec9aa6]">Course pathway <ArrowUpRight className="h-3.5 w-3.5" /></button></div></header>

    <section className="relative min-h-[650px] overflow-hidden border-b border-white/10 px-5 pb-14 pt-12 sm:px-8 lg:px-12 lg:pb-20 lg:pt-20"><img src={facility.image} alt="" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-[linear-gradient(90deg,#0d1822_0%,rgba(13,24,34,0.9)_37%,rgba(13,24,34,0.36)_100%)]" /><div className="relative mx-auto flex max-w-[1440px] flex-col justify-between gap-16"><div><button onClick={() => setLocation(campusPath)} className="inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.16em] text-[#c5d3d2] transition hover:text-[#f3e0ad]"><ArrowLeft className="h-3.5 w-3.5" /> Campus hub</button><p className="mt-20 text-[10px] font-bold uppercase tracking-[0.22em] text-[#d8bd82]">{facility.eyebrow}</p><h1 className="mt-5 max-w-4xl font-display text-[clamp(4.6rem,10vw,10rem)] leading-[0.72] tracking-[-0.06em]">{facility.label}<br /><em className="text-[#ec9aa6]">{facility.room.studioName}.</em></h1><p className="mt-10 max-w-2xl text-base leading-7 text-[#d8e2de] sm:text-lg">{facility.room.studioIntroduction}</p></div><div className="grid max-w-3xl gap-3 sm:grid-cols-3"><div className="border border-white/20 bg-[#0d1822]/72 p-4 backdrop-blur-sm"><Compass className="h-4 w-4 text-[#d8bd82]" /><p className="mt-4 text-[9px] font-bold uppercase tracking-[0.16em] text-[#d8bd82]">Learning posture</p><p className="mt-2 text-sm leading-5 text-[#dbe5e1]">Self-paced, general, non-disclosive.</p></div><div className="border border-white/20 bg-[#0d1822]/72 p-4 backdrop-blur-sm"><ShieldCheck className="h-4 w-4 text-[#d8bd82]" /><p className="mt-4 text-[9px] font-bold uppercase tracking-[0.16em] text-[#d8bd82]">Room boundary</p><p className="mt-2 text-sm leading-5 text-[#dbe5e1]">Pause and exit remain valid at every point.</p></div><div className="border border-white/20 bg-[#0d1822]/72 p-4 backdrop-blur-sm"><GraduationCap className="h-4 w-4 text-[#d8bd82]" /><p className="mt-4 text-[9px] font-bold uppercase tracking-[0.16em] text-[#d8bd82]">Mapped units</p><p className="mt-2 text-sm leading-5 text-[#dbe5e1]">{facility.courseCodes.length} units in this pathway.</p></div></div></div></section>

    <section className="px-5 py-16 sm:px-8 lg:px-12 lg:py-24"><div className="mx-auto grid max-w-[1440px] gap-10 lg:grid-cols-[0.83fr_1.17fr]"><aside className="border-t border-[#d8bd82]/45 pt-5"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#d8bd82]">Room note</p><p className="mt-5 font-display text-4xl leading-[0.91]">{facility.note}</p><button onClick={() => setLocation(pathwayPath)} className="mt-9 inline-flex items-center gap-2 bg-[#df8997] px-5 py-4 text-xs font-bold uppercase tracking-[0.14em] text-[#152532] transition hover:bg-[#eea6b1] active:scale-[0.97]">Open {facility.courseLabel} <BookOpen className="h-4 w-4" /></button></aside><div className="grid gap-3 md:grid-cols-3">{facility.room.learningModes.map((mode, index) => <article key={mode.title} className="group border border-white/10 bg-[#152532] p-6 transition hover:-translate-y-1 hover:border-[#d8bd82]/55"><span className="font-display text-5xl leading-none text-[#df8997]">0{index + 1}</span><h2 className="mt-12 font-display text-3xl leading-none">{mode.title}</h2><p className="mt-4 text-sm leading-6 text-[#c8d5d2]">{mode.copy}</p></article>)}</div></div></section>

    <section className="border-y border-white/10 bg-[#152532] px-5 py-16 sm:px-8 lg:px-12 lg:py-24"><div className="mx-auto grid max-w-[1440px] gap-10 lg:grid-cols-[0.88fr_1.12fr]"><div><p className="inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.2em] text-[#d8bd82]"><Lightbulb className="h-3.5 w-3.5" /> Studio prompts</p><h2 className="mt-5 font-display text-6xl leading-[0.82] tracking-[-0.05em]">Think without<br /><em className="text-[#ec9aa6]">telling on yourself.</em></h2><p className="mt-6 max-w-lg text-sm leading-6 text-[#c9d6d2]">Use a prompt as a private learning lens, not as an invitation to document personal experiences. There is no correct disclosure, and skipping is always valid.</p></div><div className="border border-[#d8bd82]/25 bg-[#0d1822] p-5 sm:p-7"><p className="text-[9px] font-bold uppercase tracking-[0.18em] text-[#d8bd82]">Private learning lens</p><p className="mt-5 font-display text-4xl leading-[0.95] text-[#f3f7f4]">{facility.room.reflectionPrompts[selectedPrompt]}</p><div className="mt-8 grid gap-2">{facility.room.reflectionPrompts.map((prompt, index) => <button key={prompt} onClick={() => setSelectedPrompt(index)} className={`flex items-center justify-between gap-4 border px-4 py-4 text-left text-xs leading-5 transition ${selectedPrompt === index ? "border-[#df8997] bg-[#2d1e29] text-[#f7e7eb]" : "border-white/10 text-[#c4d2ce] hover:border-[#d8bd82]/50"}`}><span>{prompt}</span><ArrowUpRight className="h-4 w-4 shrink-0" /></button>)}</div></div></div></section>

    <section className="px-5 py-16 sm:px-8 lg:px-12 lg:py-24"><div className="mx-auto grid max-w-[1440px] gap-10 xl:grid-cols-[0.74fr_1.26fr]"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#d8bd82]">Your pathway</p><h2 className="mt-5 font-display text-6xl leading-[0.82] tracking-[-0.05em]">Rooms become<br /><em className="text-[#ec9aa6]">coursework.</em></h2><p className="mt-6 max-w-md text-sm leading-6 text-[#c9d6d2]">This room curates the actual academy units below. Explore the collection at your own pace; enrolment and lesson access continue to use the existing member safeguards.</p></div><div className="grid gap-3">{facility.courseCodes.map((code, index) => { const course = courseByCode.get(code); if (!course) return null; const coursePath = `/learn?course=${encodeURIComponent(code)}&facility=${encodeURIComponent(facility.id)}${previewMode ? "&preview=academy" : ""}`; return <article key={code} className="flex flex-col gap-5 border border-white/10 bg-[#152532] p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-5"><span className="font-display text-4xl leading-none text-[#df8997]">0{index + 1}</span><div><p className="text-[9px] font-bold uppercase tracking-[0.16em] text-[#d8bd82]">{course.code} · level {course.level}</p><h3 className="mt-2 font-display text-3xl leading-none">{course.title}</h3><p className="mt-2 text-sm text-[#c7d4d0]">{course.subtitle}</p></div></div><button onClick={() => setLocation(coursePath)} className="inline-flex shrink-0 items-center gap-2 border-b border-[#d8bd82]/55 pb-1 text-[10px] font-bold uppercase tracking-[0.14em] text-[#f0d59d] transition hover:border-[#df8997] hover:text-[#ec9aa6]">View unit <ArrowUpRight className="h-3.5 w-3.5" /></button></article>; })}</div></div></section>

    <section className="border-t border-white/10 px-5 py-16 sm:px-8 lg:px-12"><div className="mx-auto max-w-[1440px]"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#d8bd82]">Faculty handoff</p><h2 className="mt-4 font-display text-5xl leading-[0.84]">Continue with<br /><em className="text-[#ec9aa6]">{facility.room.faculty.name}.</em></h2></div><button onClick={() => setLocation(facultyPath)} className="inline-flex items-center gap-2 bg-[#f0d59d] px-5 py-4 text-xs font-bold uppercase tracking-[0.14em] text-[#152532] transition hover:bg-[#f8dfab] active:scale-[0.97]">Open faculty studio <Sparkles className="h-4 w-4" /></button></div><div className="mt-8 grid gap-3 md:grid-cols-[1fr_1fr_1.3fr]"><div className="border border-white/10 bg-[#152532] p-5"><p className="text-[9px] font-bold uppercase tracking-[0.16em] text-[#d8bd82]">Faculty role</p><p className="mt-4 font-display text-3xl leading-none">{facility.room.faculty.role}</p></div><div className="border border-white/10 bg-[#152532] p-5"><p className="text-[9px] font-bold uppercase tracking-[0.16em] text-[#d8bd82]">Suggested question</p><p className="mt-4 text-sm leading-6 text-[#d7e1dc]">“{facility.room.faculty.prompt}”</p></div><div className="border border-[#d8bd82]/25 bg-[#1a2b36] p-5"><p className="text-[9px] font-bold uppercase tracking-[0.16em] text-[#d8bd82]">Scope</p><p className="mt-4 text-sm leading-6 text-[#d7e1dc]">{facility.room.faculty.handoff}</p></div></div></div></section>

    <section className="bg-[#09131b] px-5 py-14 sm:px-8 lg:px-12"><div className="mx-auto max-w-[1440px]"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#d8bd82]">Keep exploring</p><div className="mt-6 grid gap-3 md:grid-cols-3">{nearbyRooms.map((room) => <button key={room.id} onClick={() => setLocation(`/campus/${room.id}${previewMode ? "?preview=academy" : ""}`)} className="group relative min-h-[230px] overflow-hidden border border-white/10 text-left transition hover:border-[#d8bd82]/60"><img src={room.image} alt="" className="absolute inset-0 h-full w-full object-cover opacity-55 transition duration-500 group-hover:scale-[1.04] group-hover:opacity-70" /><div className="absolute inset-0 bg-[linear-gradient(0deg,rgba(8,19,27,0.94),rgba(8,19,27,0.15))]" /><span className="relative flex h-full flex-col justify-end p-5"><span className="text-[9px] font-bold uppercase tracking-[0.16em] text-[#d8bd82]">{room.eyebrow}</span><span className="mt-2 font-display text-4xl leading-none">{room.label}</span><span className="mt-5 inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.14em] text-[#f0d59d]">Enter room <ArrowUpRight className="h-3.5 w-3.5" /></span></span></button>)}</div></div></section>
    <footer className="border-t border-white/10 px-5 py-10 sm:px-8 lg:px-12"><div className="mx-auto flex max-w-[1440px] flex-col justify-between gap-5 text-xs text-[#aebfbb] sm:flex-row sm:items-center"><p>fleshsesh | academy · adult learning with agency</p><button onClick={() => setLocation(homePath)} className="inline-flex items-center gap-2 text-[#e3cc96] transition hover:text-[#ec9aa6]">Return to eCampus <ArrowUpRight className="h-3.5 w-3.5" /></button></div></footer>
  </main>;
}
