import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { ArrowLeft, ArrowUpRight, Headphones, HeartHandshake, Play, ShieldCheck } from "lucide-react";

const wordmark = "/manus-storage/fleshsesh-academy-lockup-primary_c4730d25.png";
const ageStorageKey = "fleshsesh_academy_age_confirmed_v2";

export default function Orientation() {
  const [, setLocation] = useLocation();
  const previewMode = import.meta.env.DEV && new URLSearchParams(window.location.search).get("preview") === "academy";
  const [ageReady, setAgeReady] = useState(false);
  const [ageConfirmed, setAgeConfirmed] = useState(previewMode);
  const withPreview = (path: string) => previewMode ? path + (path.includes("?") ? "&" : "?") + "preview=academy" : path;

  useEffect(() => {
    if (!previewMode) setAgeConfirmed(window.localStorage.getItem(ageStorageKey) === "true");
    setAgeReady(true);
  }, [previewMode]);

  if (!ageReady) return <div className="min-h-screen bg-[#061018]" />;
  if (!ageConfirmed) return <main className="grid min-h-screen place-items-center bg-[#061018] px-5 text-[#eff4f1]"><section className="max-w-xl border border-white/15 bg-[#0b1c26] p-8 sm:p-12"><img src={wordmark} alt="fleshsesh | academy" className="h-[96px] w-[340px] max-w-full object-cover object-center" /><p className="mt-10 text-[10px] font-bold uppercase tracking-[.22em] text-[#e6c887]">Start learning</p><h1 className="mt-4 font-display text-6xl leading-[.78] tracking-[-.05em]">Confirm the<br /><em className="text-[#e49aa9]">adult gateway.</em></h1><p className="mt-6 text-sm leading-6 text-[#c3d3cf]">The first mission and every support route share the eCampus adult-only education boundary.</p><button onClick={() => setLocation(withPreview("/"))} className="mt-9 inline-flex items-center gap-2 bg-[#e49aa9] px-5 py-4 text-xs font-bold uppercase tracking-[.14em] text-[#061018]">Return to entry <ArrowUpRight className="h-4 w-4" /></button></section></main>;

  return <main className="min-h-screen overflow-x-hidden bg-[#061018] text-[#eff4f1]"><header className="sticky top-0 z-40 border-b border-white/10 bg-[#061018]/90 backdrop-blur-xl"><div className="mx-auto flex min-h-[88px] max-w-[1500px] items-center justify-between gap-3 px-5 py-2 sm:px-8 lg:px-12"><button onClick={() => setLocation(withPreview("/"))} className="inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.14em] text-[#f1dca4]"><ArrowLeft className="h-3.5 w-3.5" /> eCampus</button><img src={wordmark} alt="fleshsesh | academy" className="h-[58px] w-[180px] object-cover object-center sm:h-[72px] sm:w-[240px]" /><button onClick={() => setLocation(withPreview("/learn"))} className="text-[10px] font-bold uppercase tracking-[.14em] text-[#f1dca4]">All units</button></div></header>

    <section className="relative min-h-[calc(100svh-88px)] overflow-hidden px-5 py-16 sm:px-8 lg:px-12 lg:py-24"><img src="/manus-storage/fleshsesh-eclinic-editorial_f01115b8.jpg" alt="" className="absolute inset-0 h-full w-full object-cover opacity-35" /><div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_26%,rgba(228,154,169,.22),transparent_26%),linear-gradient(90deg,rgba(4,13,20,.98),rgba(4,13,20,.75)_55%,rgba(4,13,20,.38))]" /><div className="relative mx-auto grid min-h-[calc(100svh-216px)] max-w-[1500px] gap-10 lg:grid-cols-[1.1fr_.62fr] lg:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[.22em] text-[#e6c887]">Your first step · about five minutes</p><h1 className="mt-7 max-w-5xl font-display text-[clamp(5rem,10vw,10rem)] leading-[.69] tracking-[-.075em]">Start one<br /><em className="text-[#e49aa9]">small mission.</em></h1><p className="mt-8 max-w-xl text-base leading-7 text-[#d1ded9]">No track to choose. No profile to complete. Begin with one simple idea about bodies, consent, communication, and wellbeing; then the next step will be clear.</p><button onClick={() => setLocation(withPreview("/learn?course=FSH%20101"))} className="mt-10 inline-flex items-center gap-3 bg-[#e49aa9] px-6 py-5 text-xs font-bold uppercase tracking-[.16em] text-[#061018]">Start my first mission <Play className="h-4 w-4 fill-current" /></button><p className="mt-5 text-[10px] leading-5 text-[#b9cbc6]">You can preview the first step without an account, enrolment, progress record, or personal disclosure.</p></div>
      <aside className="border border-white/20 bg-[#071720]/78 p-6 backdrop-blur-md"><p className="text-[9px] font-bold uppercase tracking-[.18em] text-[#e6c887]">What happens next</p><ol className="mt-6 space-y-5"><li className="flex gap-4"><span className="font-display text-5xl leading-none text-[#e6c887]">1</span><p className="pt-1 text-sm leading-6 text-[#d4dfdb]"><strong className="text-[#f5eee4]">See one idea.</strong><br />A concise explanation, not a wall of text.</p></li><li className="flex gap-4"><span className="font-display text-5xl leading-none text-[#e6c887]">2</span><p className="pt-1 text-sm leading-6 text-[#d4dfdb]"><strong className="text-[#f5eee4]">Try one action.</strong><br />A general scenario, never your personal history.</p></li><li className="flex gap-4"><span className="font-display text-5xl leading-none text-[#e6c887]">3</span><p className="pt-1 text-sm leading-6 text-[#d4dfdb]"><strong className="text-[#f5eee4]">Choose what is next.</strong><br />Continue, pause, or get simple help.</p></li></ol></aside></div></section>

    <section className="border-t border-white/10 bg-[#071720] px-5 py-12 sm:px-8 lg:px-12"><div className="mx-auto grid max-w-[1500px] gap-5 md:grid-cols-[1fr_auto_auto]"><div><p className="text-[9px] font-bold uppercase tracking-[.16em] text-[#e6c887]">Background support</p><p className="mt-3 max-w-lg text-sm leading-6 text-[#c7d6d2]">These spaces are here if you need them. You do not need to understand the campus before you start learning.</p></div><button onClick={() => setLocation(withPreview("/campus/student-services"))} className="inline-flex items-center justify-center gap-2 border border-white/20 px-5 py-4 text-[10px] font-bold uppercase tracking-[.14em] text-[#f1dca4] hover:border-[#e6c887]"><Headphones className="h-4 w-4" /> Get simple help</button><button onClick={() => setLocation(withPreview("/care"))} className="inline-flex items-center justify-center gap-2 border border-white/20 px-5 py-4 text-[10px] font-bold uppercase tracking-[.14em] text-[#f1dca4] hover:border-[#e6c887]"><HeartHandshake className="h-4 w-4" /> Care support</button></div></section>
  </main>;
}
