import { ArrowLeft, ArrowUpRight, BookOpen, Compass, Eye, ShieldCheck, Sparkles } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";
import { academyCourses } from "@shared/courseCatalog";
import { campusFacilities, type FacilityId } from "@shared/campusFacilities";

const emblem = "/manus-storage/fleshsesh-academy-emblem_79c8c72e.png";
const wordmark = "/manus-storage/fleshsesh-academy-wordmark_f79fa930.png";
const ageStorageKey = "fleshsesh_academy_age_confirmed_v2";
const shelfStorageKey = "fleshsesh_academy_syllabus_shelf_v1";

const orientationChoices: { id: FacilityId; number: string; prompt: string; title: string; copy: string }[] = [
  { id: "eclinic", number: "01", prompt: "I want a steady start", title: "Evidence & care navigation", copy: "Build a grounded base for body literacy, credible information, and knowing when education should hand over to qualified care." },
  { id: "law-library", number: "02", prompt: "I want clearer language", title: "Consent, rights & boundaries", copy: "Explore the practical language of consent, privacy, ethics, and respectful decision-making in a dark-academia study room." },
  { id: "residence-life", number: "03", prompt: "I want to understand connection", title: "Relationships & repair", copy: "Learn communication, reciprocity, body-neutral self-knowledge, and relationship repair without a performance demand." },
  { id: "esports", number: "04", prompt: "I want digital confidence", title: "Privacy & digital agency", copy: "Start with digital consent, privacy, incident-response thinking, and the consent-first culture of the Arena." },
];

function routeFromSearch() {
  const requested = new URLSearchParams(window.location.search).get("route");
  return campusFacilities.some((facility) => facility.id === requested) ? requested as FacilityId : null;
}

export default function Orientation() {
  const [, setLocation] = useLocation();
  const previewMode = import.meta.env.DEV && new URLSearchParams(window.location.search).get("preview") === "academy";
  const [ageReady, setAgeReady] = useState(false);
  const [ageConfirmed, setAgeConfirmed] = useState(previewMode);
  const [selectedId, setSelectedId] = useState<FacilityId | null>(() => routeFromSearch());
  const [shelfCodes, setShelfCodes] = useState<string[]>([]);

  useEffect(() => {
    if (!previewMode) setAgeConfirmed(window.localStorage.getItem(ageStorageKey) === "true");
    try {
      const stored = JSON.parse(window.localStorage.getItem(shelfStorageKey) ?? "[]");
      if (Array.isArray(stored) && stored.every((item) => typeof item === "string")) setShelfCodes(stored);
    } catch { setShelfCodes([]); }
    setAgeReady(true);
  }, [previewMode]);

  const selected = useMemo(() => campusFacilities.find((facility) => facility.id === selectedId) ?? null, [selectedId]);
  const savedCourses = academyCourses.filter((course) => shelfCodes.includes(course.code));
  const previewQuery = previewMode ? "?preview=academy" : "";
  const withPreview = (path: string) => previewMode ? `${path}${path.includes("?") ? "&" : "?"}preview=academy` : path;
  const selectRoute = (id: FacilityId) => {
    setSelectedId(id);
    const url = new URL(window.location.href);
    url.searchParams.set("route", id);
    window.history.replaceState(null, "", `${url.pathname}${url.search}${url.hash}`);
    window.setTimeout(() => document.getElementById("selected-route")?.scrollIntoView({ behavior: "smooth", block: "start" }), 0);
  };
  const toggleShelf = (courseCode: string) => setShelfCodes((current) => {
    const next = current.includes(courseCode) ? current.filter((code) => code !== courseCode) : [...current, courseCode];
    window.localStorage.setItem(shelfStorageKey, JSON.stringify(next));
    return next;
  });

  if (!ageReady) return <div className="min-h-screen bg-[#061018]" />;
  if (!ageConfirmed) return <main className="grid min-h-screen place-items-center bg-[#061018] px-5 text-[#eff4f1]"><section className="max-w-xl border border-white/15 bg-[#0b1c26] p-8 sm:p-12"><img src={wordmark} alt="fleshsesh | academy" className="h-12 w-[210px] object-contain object-left" /><p className="mt-10 text-[10px] font-bold uppercase tracking-[.22em] text-[#e6c887]">Route discovery</p><h1 className="mt-4 font-display text-6xl leading-[.78] tracking-[-.05em]">Start after the<br /><em className="text-[#e49aa9]">adult gateway.</em></h1><p className="mt-6 text-sm leading-6 text-[#c3d3cf]">Choose a visual learning route after confirming the academy’s adult-only entry boundary.</p><button onClick={() => setLocation("/")} className="mt-9 inline-flex items-center gap-2 bg-[#e49aa9] px-5 py-4 text-xs font-bold uppercase tracking-[.14em] text-[#061018]">Return to entry <ArrowUpRight className="h-4 w-4" /></button></section></main>;

  return <main className="min-h-screen overflow-x-hidden bg-[#061018] text-[#eff4f1]"><header className="sticky top-0 z-40 border-b border-white/10 bg-[#061018]/90 backdrop-blur-xl"><div className="mx-auto flex h-[74px] max-w-[1600px] items-center justify-between px-5 sm:px-8 lg:px-12"><button onClick={() => setLocation(`/${previewQuery}`)} className="inline-flex items-center gap-3 text-[10px] font-bold uppercase tracking-[.15em] text-[#f1dca4]"><img src={emblem} alt="" className="h-8 w-8 rounded-full ring-1 ring-[#e6c887]/55" /> eCampus home</button><img src={wordmark} alt="fleshsesh | academy" className="h-8 w-[145px] object-contain" /><button onClick={() => setLocation(withPreview("/learn"))} className="inline-flex items-center gap-2 border-b border-[#e6c887]/60 pb-1 text-[10px] font-bold uppercase tracking-[.14em] text-[#f1dca4]">Full atlas <ArrowUpRight className="h-3.5 w-3.5" /></button></div></header>

    <section className="relative overflow-hidden px-5 pb-16 pt-16 sm:px-8 lg:px-12 lg:pb-24 lg:pt-24"><img src={selected?.image ?? campusFacilities[1].image} alt="" className="absolute inset-0 h-full w-full object-cover opacity-36" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(4,13,20,.98),rgba(4,13,20,.76)_48%,rgba(4,13,20,.22))]" /><div className="relative mx-auto grid max-w-[1600px] gap-10 lg:grid-cols-[1fr_.62fr] lg:items-end"><div><p className="inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.22em] text-[#e6c887]"><Compass className="h-3.5 w-3.5" /> Quiet orientation · no personal story required</p><h1 className="mt-7 max-w-5xl font-display text-[clamp(5rem,10vw,10rem)] leading-[.7] tracking-[-.075em]">Find a place<br /><em className="text-[#e49aa9]">to begin.</em></h1><p className="mt-8 max-w-2xl text-base leading-7 text-[#d1ded9]">Choose the learning conversation that feels most useful right now. This is not a quiz, diagnosis, or profile. Your choice stays in this browser session and never changes your access.</p></div><aside className="border border-white/20 bg-[#071720]/72 p-6 backdrop-blur-md"><p className="inline-flex items-center gap-2 text-[9px] font-bold uppercase tracking-[.17em] text-[#e6c887]"><Eye className="h-3.5 w-3.5" /> Privacy by design</p><p className="mt-5 font-display text-5xl leading-[.82]">Pick a subject,<br />not a <em className="text-[#e49aa9]">disclosure.</em></p><p className="mt-5 text-xs leading-5 text-[#c7d6d2]">No questions about your body, relationships, identity, history, or activity are collected here.</p></aside></div></section>

    <section className="px-5 py-16 sm:px-8 lg:px-12 lg:py-24"><div className="mx-auto max-w-[1600px]"><div className="flex flex-col gap-5 border-b border-white/10 pb-8 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.22em] text-[#e6c887]">Four starting conversations</p><h2 className="mt-4 font-display text-6xl leading-[.78] tracking-[-.055em]">Choose an<br /><em className="text-[#e49aa9]">entry lens.</em></h2></div><p className="max-w-md text-sm leading-6 text-[#bfcfca]">Each lens opens an existing campus world and its mapped units. You can change direction or browse the full atlas at any point.</p></div><div className="mt-8 grid gap-3 md:grid-cols-2">{orientationChoices.map((choice) => { const facility = campusFacilities.find((item) => item.id === choice.id)!; const isSelected = selectedId === choice.id; return <button key={choice.id} onClick={() => selectRoute(choice.id)} className={`group relative min-h-[340px] overflow-hidden border p-6 text-left transition ${isSelected ? "border-[#e49aa9]" : "border-white/10 hover:border-[#e6c887]/70"}`} aria-pressed={isSelected}><img src={facility.image} alt="" className="absolute inset-0 h-full w-full object-cover opacity-50 transition duration-700 group-hover:scale-[1.05] group-hover:opacity-65" /><div className="absolute inset-0 bg-[linear-gradient(0deg,rgba(4,13,20,.97),rgba(4,13,20,.18)_80%)]" /><div className="relative flex h-full flex-col"><span className="font-display text-5xl text-[#e6c887]">{choice.number}</span><p className="mt-auto text-[9px] font-bold uppercase tracking-[.18em] text-[#e6c887]">{choice.prompt}</p><h3 className="mt-3 font-display text-5xl leading-[.8]">{choice.title}</h3><p className="mt-4 max-w-lg text-xs leading-5 text-[#d5e0dc]">{choice.copy}</p><span className="mt-6 inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.14em] text-[#f1dca4]">{isSelected ? "Route selected" : "Select this route"} <ArrowUpRight className="h-3.5 w-3.5" /></span></div></button>})}</div></div></section>

    <section id="selected-route" className="relative overflow-hidden border-y border-white/10 bg-[#102630] px-5 py-16 sm:px-8 lg:px-12 lg:py-24"><img src={selected?.image ?? campusFacilities[0].image} alt="" className="pointer-events-none absolute inset-y-0 right-0 h-full w-[44%] object-cover opacity-25" /><div className="pointer-events-none absolute inset-y-0 right-0 w-[65%] bg-[linear-gradient(90deg,#102630,rgba(16,38,48,.38))]" />{selected ? <div className="relative mx-auto grid max-w-[1600px] gap-8 lg:grid-cols-[1fr_.65fr] lg:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[.22em] text-[#e6c887]">Your selected route · {selected.eyebrow}</p><h2 className="mt-5 font-display text-7xl leading-[.76] tracking-[-.06em]">{selected.label}<br /><em className="text-[#e49aa9]">starts here.</em></h2><p className="mt-7 max-w-2xl text-base leading-7 text-[#d0ded9]">{selected.description} The first mapped units are <strong className="text-[#f1dca4]">{selected.courseCodes.slice(0, 2).join(" and ")}</strong>; you can enter the room or open every unit in this pathway.</p><div className="mt-7 flex flex-wrap gap-2">{selected.courseCodes.map((code) => <button key={code} onClick={() => toggleShelf(code)} className={`inline-flex items-center gap-2 border px-3 py-2 text-[10px] font-bold uppercase tracking-[.12em] ${shelfCodes.includes(code) ? "border-[#e49aa9] bg-[#3a2230] text-[#f2c7cf]" : "border-white/20 text-[#d1dfda] hover:border-[#e6c887]"}`}><BookOpen className="h-3.5 w-3.5" />{shelfCodes.includes(code) ? `Remove ${code}` : `Save ${code}`}</button>)}</div></div><div className="grid gap-3"><button onClick={() => setLocation(withPreview(`/campus/${selected.id}`))} className="group flex items-center justify-between bg-[#e6c887] px-5 py-5 text-left text-xs font-bold uppercase tracking-[.14em] text-[#061018]">Enter {selected.label}<ArrowUpRight className="h-4 w-4 transition group-hover:translate-x-1 group-hover:-translate-y-1" /></button><button onClick={() => setLocation(withPreview(`/learn?facility=${selected.id}`))} className="group flex items-center justify-between border border-white/25 px-5 py-5 text-left text-xs font-bold uppercase tracking-[.14em] text-[#f1f3ed] transition hover:border-[#e6c887] hover:text-[#f1dca4]">Open mapped units<Sparkles className="h-4 w-4" /></button></div></div> : <div className="relative mx-auto flex max-w-[1600px] items-center gap-4 border border-white/15 bg-[#071720]/65 p-6 text-sm leading-6 text-[#d2dfdb]"><ShieldCheck className="h-5 w-5 shrink-0 text-[#e6c887]" />Select a learning conversation above to see its room and mapped units. Nothing is saved or inferred from your selection.</div>}</section>

    <section className="bg-[#071720] px-5 py-14 sm:px-8 lg:px-12"><div className="mx-auto grid max-w-[1600px] gap-7 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><p className="inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.2em] text-[#e6c887]"><BookOpen className="h-3.5 w-3.5" /> Private syllabus shelf</p><h2 className="mt-5 font-display text-6xl leading-[.8]">Keep a<br /><em className="text-[#e49aa9]">thread.</em></h2><p className="mt-6 max-w-md text-sm leading-6 text-[#c7d6d2]">Saved units live only in this browser as course codes. They do not create a member account, enrolment, progress record, or personal profile. Clearing browser storage removes them.</p></div><div className="border border-white/15 bg-[#061018] p-5 sm:p-7">{savedCourses.length ? <div className="grid gap-2 sm:grid-cols-2">{savedCourses.map((course) => <button key={course.code} onClick={() => setLocation(withPreview(`/learn?course=${encodeURIComponent(course.code)}`))} className="group flex items-start justify-between border border-white/10 p-4 text-left transition hover:border-[#e6c887]/70"><span><span className="text-[9px] font-bold uppercase tracking-[.14em] text-[#e6c887]">{course.code}</span><span className="mt-2 block font-display text-3xl leading-[.85]">{course.title}</span></span><ArrowUpRight className="h-4 w-4 shrink-0 text-[#e49aa9]" /></button>)}</div> : <div className="flex min-h-32 items-center gap-3 text-sm leading-6 text-[#b9cbc6]"><ShieldCheck className="h-5 w-5 shrink-0 text-[#e6c887]" />No saved units yet. Select a route and save a course code if you want a private return point on this device.</div>}</div></div></section>
    <footer className="bg-[#030b11] px-5 py-8 sm:px-8 lg:px-12"><div className="mx-auto flex max-w-[1600px] items-center justify-between gap-4 text-[10px] font-bold uppercase tracking-[.14em] text-[#9fb3b0]"><button onClick={() => setLocation(`/${previewQuery}`)} className="inline-flex items-center gap-2 text-[#f1dca4]"><ArrowLeft className="h-3.5 w-3.5" /> eCampus home</button><span>fleshsesh | academy · orientation</span></div></footer></main>;
}
