export type CourseLevel = "101" | "201" | "301" | "401";

export type TeachingModule = {
  id: string;
  title: string;
  objective: string;
  minutes: number;
  summary: string;
  practice: string;
  check: string;
  xp: number;
};

export type AcademyCourse = {
  code: string;
  level: CourseLevel;
  title: string;
  subtitle: string;
  hours: number;
  priceCents: number;
  currency: "aud";
  prerequisites: string;
  learningOutcome: string;
  assessment: string;
  badgeCode: string;
  modules: TeachingModule[];
};

type CourseInput = Omit<AcademyCourse, "modules"> & { modules: [string, string, string, string, string, string] | [string, string, string, string, string, string, string] | [string, string, string, string, string, string, string, string] };

const module = (courseCode: string, position: number, title: string, courseTitle: string): TeachingModule => ({
  id: `${courseCode.toLowerCase().replace(/\s/g, "-")}-m${position}`,
  title,
  objective: `Explain ${title.toLowerCase()} in clear, evidence-aware language.`,
  minutes: 7,
  summary: `${title} places ${courseTitle.toLowerCase()} in an inclusive, evidence-aware learning context. Work through the plain-language explanation, identify uncertainty, and distinguish general education from individual clinical or legal advice.`,
  practice: `Use the guided scenario to apply ${title.toLowerCase()} to a fictional learner case. You may choose the non-disclosure alternative; personal sexual, health, or relationship details are never required.`,
  check: `Complete the short knowledge check, then explain one safe next step or referral boundary in your own words.`,
  xp: 35,
});

const course = (input: CourseInput): AcademyCourse => ({ ...input, modules: input.modules.map((title, index) => module(input.code, index + 1, title, input.title)) });

export const academyCourses: AcademyCourse[] = [
  course({ code: "FSH 101", level: "101", title: "Body Literacy", subtitle: "Human anatomy and physiology", hours: 12, priceCents: 4900, currency: "aud", prerequisites: "None", learningOutcome: "Explain foundational anatomy, variation, life stages and help-seeking boundaries in plain language.", assessment: "Anatomy-labeling quiz, myth correction and symptom-boundary scenario.", badgeCode: "body-literacy", modules: ["Body terminology and variation", "Internal and external anatomy across bodies", "Puberty, hormones and life stages", "Sexual response and pleasure diversity", "Menstruation, menopause and reproductive aging", "Body image, media literacy and help-seeking"] }),
  course({ code: "FSH 102", level: "101", title: "Consent, Boundaries & Communication", subtitle: "Practical consent literacy", hours: 10, priceCents: 4900, currency: "aud", prerequisites: "None", learningOutcome: "Use clear requests, check-ins, boundary statements and repair language while recognising coercion and incapacity.", assessment: "Branching consent simulations and a written communication script.", badgeCode: "consent-communicator", modules: ["Consent principles", "Verbal and non-verbal communication", "Negotiating uncertainty and changing minds", "Pressure, coercion and incapacity", "Boundary scripts", "Repair and accountability"] }),
  course({ code: "FSH 103", level: "101", title: "Sexual Health, Hygiene & Self-Care", subtitle: "Body-neutral preventive care", hours: 8, priceCents: 4900, currency: "aud", prerequisites: "None", learningOutcome: "Separate preventive-care principles from shame-based myths and identify when a clinician is the right next step.", assessment: "Preventive-care checklist and referral-navigation exercise.", badgeCode: "health-navigator", modules: ["Hygiene myths and body neutrality", "Skin, mucosal, menstrual and oral health", "Products, irritation and allergies", "Pain, bleeding, discharge and warning signs", "Vaccination and preventive care", "Preparing for a health appointment"] }),
  course({ code: "FSH 104", level: "101", title: "Relationships, Identity & Respect", subtitle: "Diversity and reciprocity", hours: 9, priceCents: 4900, currency: "aud", prerequisites: "None", learningOutcome: "Recognise respectful relationship qualities, diverse identities and structures, and the influence of social expectations.", assessment: "Inclusive case analysis.", badgeCode: "inclusive-practice", modules: ["Friendship, intimacy and family", "Orientation, identity and expression", "Monogamy, non-monogamy and chosen family", "Gender norms and power", "Respect, inclusion and discrimination", "Personal values without imposing them on others"] }),
  course({ code: "FSH 105", level: "101", title: "STI & HIV Prevention Essentials", subtitle: "Prevention and care literacy", hours: 10, priceCents: 4900, currency: "aud", prerequisites: "None", learningOutcome: "Explain prevention layers, testing and treatment principles, stigma reduction and trusted-service navigation.", assessment: "Prevention-plan scenario and source-evaluation quiz.", badgeCode: "sti-prevention-literate", modules: ["What STIs are", "Routes and risk reduction", "Barriers as one prevention layer", "Testing and treatment principles", "HIV prevention and care literacy", "Talking with partners and providers"] }),
  course({ code: "FSH 201", level: "201", title: "Contraception & Family Planning", subtitle: "Options, access and referral", hours: 14, priceCents: 5900, currency: "aud", prerequisites: "FSH 101 or placement", learningOutcome: "Compare contraceptive categories and prepare informed questions for professional care without individual prescribing.", assessment: "Comparison matrix and provider-question brief.", badgeCode: "health-navigator", modules: ["Pregnancy and fertility basics", "Barrier, hormonal, intrauterine, behavioural and permanent methods", "Access, adherence, side effects and myths", "Emergency contraception and pregnancy testing", "Preconception, pregnancy options and loss", "Inclusive family-building pathways"] }),
  course({ code: "FSH 202", level: "201", title: "STI Testing, Treatment & Care Navigation", subtitle: "Service access and communication", hours: 12, priceCents: 5900, currency: "aud", prerequisites: "FSH 105", learningOutcome: "Build a testing conversation, understand general test categories and navigate a referral directory without diagnosis.", assessment: "Simulated clinic intake and referral plan.", badgeCode: "health-navigator", modules: ["Testing pathways", "Symptoms, asymptomatic infection and uncertainty", "Treatment adherence and follow-up", "Partner notification and stigma", "HIV testing, prevention and care", "Service-access barriers and advocacy"] }),
  course({ code: "FSH 203", level: "201", title: "Pleasure, Intimacy & Sexual Communication", subtitle: "Non-pressured intimacy literacy", hours: 12, priceCents: 5900, currency: "aud", prerequisites: "FSH 102", learningOutcome: "Communicate preferences and limits without entitlement while recognising desire diversity and contextual influences.", assessment: "Inclusive intimacy-plan template and reflective analysis.", badgeCode: "pleasure-positive-communicator", modules: ["Pleasure literacy", "Desire and arousal diversity", "Asking, listening and checking in", "Body image and self-compassion", "Pain, accessibility and professional support", "Intimacy beyond performance"] }),
  course({ code: "FSH 204", level: "201", title: "Relationship Dynamics & Conflict Repair", subtitle: "Listening, repair and safety", hours: 12, priceCents: 5900, currency: "aud", prerequisites: "FSH 104 and FSH 102", learningOutcome: "Analyse conflict patterns, practise repair and recognise when coercion or violence requires specialist support.", assessment: "Case formulation and repair script.", badgeCode: "consent-communicator", modules: ["Relationship systems and expectations", "Conflict cycles", "Listening and validation", "Repair, accountability and forgiveness", "Jealousy, agreements and autonomy", "Coercion, violence and referral"] }),
  course({ code: "FSH 205", level: "201", title: "LGBTQ+ Inclusive Sexual Health", subtitle: "Affirming health and service design", hours: 11, priceCents: 5900, currency: "aud", prerequisites: "FSH 101", learningOutcome: "Use respectful language and build communication and referral approaches that affirm diverse learners.", assessment: "Service-redesign brief.", badgeCode: "inclusive-practice", modules: ["Language and identity", "Inclusive anatomy and health communication", "Screening across bodies and practices", "Gender-affirming and respectful care principles", "Minority stress and resilience", "Inclusive institution design"] }),
  course({ code: "FSH 206", level: "201", title: "Digital Intimacy, Privacy & Safety", subtitle: "Digital consent and response planning", hours: 10, priceCents: 5900, currency: "aud", prerequisites: "FSH 102", learningOutcome: "Assess privacy and consent in digital communication and create a safe incident-response plan.", assessment: "Branching incident simulation and personal safety checklist.", badgeCode: "digital-intimacy-safety", modules: ["Digital consent", "Metadata, accounts and privacy", "Image-based abuse and reporting", "Dating-app safety and fraud", "Sextortion and coercive threats", "Evidence preservation, support and recovery"] }),
  course({ code: "FSH 207", level: "201", title: "Sexual Wellness & Mental Health", subtitle: "Supportive communication and referral", hours: 11, priceCents: 5900, currency: "aud", prerequisites: "FSH 102", learningOutcome: "Connect sexual wellbeing with mental health, use supportive language and identify qualified-care pathways.", assessment: "Supportive-response exercise and referral map.", badgeCode: "health-navigator", modules: ["Definitions of sexual wellbeing", "Stress, mood, medication and desire", "Shame and self-compassion", "Trauma-aware communication", "Sexual pain and health referrals", "Crisis, abuse and support pathways"] }),
  course({ code: "FSH 301", level: "301", title: "Reproductive Health, Fertility & Life Planning", subtitle: "Uncertainty-aware life planning", hours: 14, priceCents: 6900, currency: "aud", prerequisites: "FSH 201", learningOutcome: "Explain fertility variation, reproductive pathways and uncertainty sensitively while maintaining clinical referral boundaries.", assessment: "Life-planning case brief with clinical-referral boundaries.", badgeCode: "health-navigator", modules: ["Fertility biology", "Cycles and fertility awareness", "Preconception health", "Infertility and assisted reproduction orientation", "Fertility preservation and reproductive aging", "Pregnancy, loss, parenting and non-parenthood"] }),
  course({ code: "FSH 302", level: "301", title: "Kink Education, Negotiation & Safety", subtitle: "Adult-only risk literacy", hours: 14, priceCents: 6900, currency: "aud", prerequisites: "FSH 102 and FSH 204; adult learners only", learningOutcome: "Compare SSC and RACK, conduct a non-explicit negotiation and recognise when risk or coercion requires stopping and seeking help.", assessment: "Safety-negotiation simulation and risk matrix.", badgeCode: "kink-safety-literate", modules: ["Terminology and anti-stigma principles", "Consent and power exchange", "SSC and RACK comparison", "Negotiation, limits and safewords", "Risk assessment, hygiene and injury prevention", "Aftercare, debriefing, privacy and community ethics"] }),
  course({ code: "FSH 303", level: "301", title: "Communication for Educators & Advocates", subtitle: "Bounded education and facilitation", hours: 16, priceCents: 6900, currency: "aud", prerequisites: "Any two 201 courses", learningOutcome: "Translate evidence into plain language, facilitate inclusive discussion and refer beyond personal competence.", assessment: "Ten-minute teaching demonstration and lesson plan.", badgeCode: "peer-educator", modules: ["Adult-learning theory", "Facilitation and psychological safety", "Difficult questions", "Misinformation and source checking", "Inclusive and accessible teaching", "Safeguarding and referral", "Micro-teaching practicum"] }),
  course({ code: "FSH 304", level: "301", title: "Sexual Rights, Ethics, Power & Social Context", subtitle: "Rights-respecting analysis", hours: 13, priceCents: 6900, currency: "aud", prerequisites: "FSH 104 and FSH 205", learningOutcome: "Analyse power, rights, technology and institutional context to propose ethically bounded interventions.", assessment: "Policy critique and stakeholder presentation.", badgeCode: "community-advocate", modules: ["Rights, autonomy and dignity", "Gender and power", "Stigma and structural barriers", "Violence, exploitation and safeguarding", "Privacy, data and AI ethics", "Advocacy and institutional accountability"] }),
  course({ code: "FSH 305", level: "301", title: "Inclusive Service & Curriculum Design", subtitle: "Accessible learning design", hours: 15, priceCents: 6900, currency: "aud", prerequisites: "FSH 303", learningOutcome: "Design accessible activities, competency maps, referral pathways and an evidence-aware evaluation plan.", assessment: "Complete mini-course prototype.", badgeCode: "curriculum-designer", modules: ["Needs and audience analysis", "Curriculum mapping", "Universal design", "Case and simulation design", "Clinical and safeguarding review", "Implementation planning", "Evaluation and iteration"] }),
  course({ code: "FSH 401", level: "401", title: "Advanced Advocacy & Community Practice", subtitle: "Community intervention and evaluation", hours: 18, priceCents: 7900, currency: "aud", prerequisites: "FSH 303 and FSH 304", learningOutcome: "Co-design a rights-respecting intervention, partnership plan and outcome evaluation with communities.", assessment: "Supervised advocacy proposal and oral defense.", badgeCode: "community-advocate", modules: ["Community assessment", "Stakeholder and power mapping", "Program logic", "Partnership and referral networks", "Communications and media", "Implementation risks", "Outcome evaluation", "Capstone defense"] }),
  course({ code: "FSH 402", level: "401", title: "Advanced Consent & Relationship Facilitation", subtitle: "Complex conversations and referral", hours: 16, priceCents: 7900, currency: "aud", prerequisites: "FSH 204 and FSH 303", learningOutcome: "Facilitate complex consent conversations and apply survivor-centred escalation and referral protocols.", assessment: "Observed facilitation using a standardised rubric.", badgeCode: "consent-communicator", modules: ["Advanced consent theory", "Power and capacity", "Conflict mediation boundaries", "Neurodivergent communication", "Sexual and reproductive coercion", "Survivor-centred referral", "Supervised facilitation lab"] }),
  course({ code: "FSH 403", level: "401", title: "Evidence, Evaluation & AI in Sexual Education", subtitle: "Research and AI governance", hours: 18, priceCents: 7900, currency: "aud", prerequisites: "FSH 305", learningOutcome: "Appraise evidence, audit AI for bias and design ethical learner analytics and content-update practices.", assessment: "Evidence audit and AI safety review.", badgeCode: "curriculum-designer", modules: ["Evidence hierarchies", "Systematic reviews and guideline reading", "Measurement and survey design", "Bias, privacy and algorithmic accountability", "Human-in-the-loop AI", "Clinical update governance", "Evaluation report"] }),
  course({ code: "FSH 404", level: "401", title: "Capstone: Sexual Wellness Education Portfolio", subtitle: "Supervised portfolio practice", hours: 24, priceCents: 7900, currency: "aud", prerequisites: "Selected certification track and capstone approval", learningOutcome: "Integrate evidence, inclusion, ethics, safeguarding and referral practice into a structured educational portfolio.", assessment: "Portfolio, implementation plan, evidence appendix and viva-style defence.", badgeCode: "curriculum-designer", modules: ["Proposal and scope", "Literature and needs review", "Prototype development", "Accessibility and safeguarding audit", "Pilot feedback", "Revision", "Final presentation and reflective defence"] }),
];

export const courseByCode = new Map(academyCourses.map(course => [course.code, course]));

export function getCourse(courseCode: string) {
  return courseByCode.get(courseCode);
}

export function formatCoursePrice(course: AcademyCourse) {
  return new Intl.NumberFormat("en-AU", { style: "currency", currency: course.currency.toUpperCase(), maximumFractionDigits: 0 }).format(course.priceCents / 100);
}
